In [2]:
!pip install torch

^C


In [3]:
import torch
import torch.nn as nn

In [4]:
# 创建一个 Softmax 实例
softmax = nn.Softmax(dim=1)

In [5]:
# 假设我们有一个输入张量，形状为 (batch_size, num_classes)
# 这里我们创建一个示例张量，包含了一些随机分数
batch_size = 3
num_classes = 5
input_tensor = torch.randn(batch_size, num_classes)

In [7]:
# 应用 softmax 激活函数
output = softmax(input_tensor)

In [8]:
print("Input tensor:")
print(input_tensor)

Input tensor:
tensor([[-0.6532, -1.3961,  0.2941, -0.4275,  0.0099],
        [-1.3046,  0.6299,  0.3587, -1.3999,  1.3102],
        [ 0.0487,  1.1105,  0.0727, -0.4059, -0.0076]])


In [11]:
print("\nOutput tensor after applying softmax:")
print(output)


Output tensor after applying softmax:
tensor([[0.1380, 0.0656, 0.3558, 0.1729, 0.2678],
        [0.0360, 0.2492, 0.1900, 0.0327, 0.4920],
        [0.1539, 0.4451, 0.1577, 0.0977, 0.1455]])


In [12]:

# 验证 softmax 输出的每个样本的概率和是否为 1
print("\nSum of probabilities for each sample (should be close to 1):")
print(output.sum(dim=1))


Sum of probabilities for each sample (should be close to 1):
tensor([1.0000, 1.0000, 1.0000])
